name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DOCR with Access Token
        run: |
          echo ${{ secrets.DOCR_TOKEN }} | docker login registry.digitalocean.com -u ${{ secrets.DOCR_TOKEN }} --password-stdin

      - name: Build Docker Image
        run: docker build -t registry.digitalocean.com/dc-containers-test/hello-node-app:latest .

      - name: Push Docker Image to DOCR
        run: docker push registry.digitalocean.com/dc-containers-test/hello-node-app:latest
